name: drupalcz
type: drupal10
docroot: docroot
php_version: "8.3"
webserver_type: apache-fpm
nodejs_version: "18"
# Non-default: 80/443 are taken by the traefik proxy on the lkv host.
router_http_port: "8080"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []

hooks:
  post-start:
    - exec: scripts/create-settings.sh
