---
# Triggers the workflow on push or delete events, and validates pull requests.
on:
  push:
  delete:
  pull_request:
name: Build

jobs:
  validate:
    name: Validate Composer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: mbstring, gd, intl, yaml, bcmath, curl
      - name: Validate composer.json, composer.lock and platform requirements
        if: "!contains(github.ref, 'refs/tags/') && github.event_name != 'delete'"
        run: |
          composer validate
          composer check-platform-reqs
    # - name: Fail if branch name does not match pantheon limitations
    #   run: TODO

  gitsync:
    if: github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'develop')
    name: Build and push repo
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup PHP and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: mbstring, gd, intl, yaml, bcmath, curl
      - name: Execute build script
        env:
          GIT_REMOTE: ${{ secrets.GIT_REMOTE_HOSTING }}
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CIDRUPALCZPRIVATE }}
          GH_EVENT_REF: ${{ github.event.ref }}
          GH_EVENT_REF_TYPE: ${{ github.event.ref_type }}
        run: ./.github/scripts/build.sh
